name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Node 20
      - name: Use Node.js 20.0
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          export CI=false
          npm run build

      - name: Zip build folder
        run: |
          cd dist
          zip -r ../publish.zip .
          cd ..

      - name: Deploy to b4rify.com
        run: |
          curl -k -X POST "https://CloudHostingAPI.b4rify.com/api/deploy" \
            -H "X-Version: 1988" \
            -H "X-Subdomain: mateusz-wolnica.b4rify.com" \
            -F "uploads=@publish.zip" \
